export const sliderList = [
	{
		avatar: '/user/user-2.png',
		name: 'Ben Yardley',
		city: 'Київ - Кишинів',
		date: '1 May 2023',
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		rating: 5,
	},
	{
		avatar: '/user/user-3.png',
		name: 'Craig Martin',
		city: 'Львів - Париж',
		date: '1 May 2023',
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		rating: 5,
	},
	{
		avatar: '/user/user-1.jpg',
		name: 'Юлiя',
		city: 'Днiпро - Париж',
		date: '6 May 2023',
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		rating: 4,
	},
	{
		avatar: '/user/user-2.png',
		name: 'Ben Yardley',
		city: 'Київ - Кишинів',
		date: '1 May 2023',
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		rating: 5,
	},
	{
		avatar: '/user/user-3.png',
		name: 'Craig Martin',
		city: 'Львів - Париж',
		date: '1 May 2023',
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
		rating: 5,
	},
	{
		avatar: '/user/user-1.jpg',
		name: 'Юлiя',
		city: 'Днiпро - Париж',
		date: '6 May 2023',
		text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
		rating: 4,
	},
];
